### ISSUE TITLE
(regression) Protobuf.decode cannot works with enum used as objects field's type

### ISSUE THREAD

**Issue by jangko** [status-im/nim-protobuf-serialization#8]
it works before, but now it cannot compile

```Nim
import options
import protobuf_serialization

type
  Color {.pure.} = enum
    RED
    GREEN
    
  Apple {.protobuf3.} = object
    color {. fieldNumber: 12.}: Color

var msg: string
let y = Protobuf.decode(msg, Apple)
```

error messages:
```text
Error: Encoding specified for an already wrapped type, or a type which isn't wrappable due to always having one encoding (byte, char, bool, or float).
```

**Comment by jangko** [comment]
@kayabaNerve, your last PR seems introduce this regression

**Comment by kayabaNerve** [comment]
Thanks for catching this. Adding support for Protobuf 3 file parsing changed how enums needed to be handled, in order to support the spec more accurately. These changes look good to me, and I'm sorry this occurred.

**Comment by jangko** [comment]
Update: when I try to run protobuf conformance test, turn out enum is encoded as `PInt` and not as `Sint`, fixed in #10.

**Comment by kayabaNerve** [comment]
The Protobuf documentation specifically says enums are PInt.

https://developers.google.com/protocol-buffers/docs/proto#enum

> Enumerator constants must be in the range of a 32-bit integer. Since enum values use varint encoding on the wire, negative values are inefficient and thus not recommended. You can define enums within a message definition, as in the above example, or outside – these enums can be reused in any message definition in your .proto file. You can also use an enum type declared in one message as the type of a field in a different message, using the syntax _MessageType_._EnumType_.

This was one of the changes made with support for Protobuf 3 files, a correction for accurate support, and is the reason why this regression occurred. Mind if I ask where you got the info they should be SInt?

Speaking of, your commit makes enums use SInt. If I'm correct, then this change would get it to compile, yet would also break enum enocding. That said, it's easy enough to replace the template.

**Comment by jangko** [comment]
What I mean is enum should be encoded as PInt but your code classify enum as SInt. Initially I don't put much attention to encoding. But now i have fixed it using proper encoding.

**Comment by kayabaNerve** [comment]
Total accident. That's on me. I meant to append it to the line after. That definition in VarInt needs to be corrected... Your commit still looks great, except for the continuation of my mistake. I'd be happy to append to it to resolve this.
